inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  Exclude:
    - lib/generators/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.3

Layout/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/StderrPuts:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
