inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  Exclude:
    - gemfiles/vendor/bundle/**/* # This dir only shows up on Travis
    - lib/generators/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.3

LineLength:
  Enabled: false

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/StderrPuts:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
